version: '3.9'

services:
  blackbox:
    image: prom/blackbox-exporter:v0.22.0
    container_name: blackbox
    restart: always
    ports:
      - '9115:9115'
    volumes:
      - ./configs/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - quarks


  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    restart: always
    ports:
      - '9090:9090'
    volumes:
      - ./configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./configs/prometheus/alertrules.yml:/etc/prometheus/alertrules.yml
      - prometheus_data:/prometheus
    command: 
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - quarks


  grafana:
    image: grafana/grafana:9.1.5
    container_name: grafana
    depends_on:
      - prometheus
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    # env_file: .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - quarks


  alertmanager:
    image: prom/alertmanager:v0.24.0
    container_name: alertmanager
    volumes:
      - ./configs/alertmanager/alertmanager.yml:/etc/alertmanager/config/alertmanager.yml
      - ./configs/alertmanager/notifications.tmpl:/etc/alertmanager/config/notifications.tmpl
    command:
      - "--config.file=/etc/alertmanager/config/alertmanager.yml"
    restart: always
    ports:
      - '9093:9093'
    networks:
      - quarks
    labels:
      org.label-schema.group: "monitoring"


  flask-api:
    image: spytliak/genesis-flask-rest-api:v1
    container_name: quarks
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_ENVIRONMENT: "dev"
      FLASK_APP: "api.py"
    healthcheck:
      test: ["CMD", "curl", "-f", "0.0.0.0:5000"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 15s
    networks:
      - quarks

networks:
  quarks:
    name: monitoring

volumes:
  prometheus_data: {}
  grafana_data: {}