global:
  scrape_interval: 15s 
  evaluation_interval: 15s

rule_files:
  - alertrules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: "blackbox"
    metrics_path: /probe
    params: 
      module: [http_2xx]
    static_configs:
      - targets: ["https://github.com/", "http://quarks:5000/"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        target_label: target
      - target_label: __address__
        replacement: blackbox:9115
