{
 "title": "Quarks Homework",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Quarks Global Duration",
   "type": "timeseries",
   "description": "Quarks DevOps Days",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "probe_duration_seconds{}", "legendFormat": "{{ target }}" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "probe_success{}", "legendFormat": "{{target}}" }
   ]
  },
  {
   "title": "Quarks HTTP Duration - Differences  (phase = All)",
   "type": "timeseries",
   "description": "Quarks DevOps Days",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{} - probe_http_duration_seconds{} offset 1d",
     "legendFormat": "{{ phase }} - {{target}}"
    }
   ]
  }
 ]
}